---
- name: Remove old network
  file:
    path={{ item }}
    state=absent
  with_items:
    - /etc/sysconfig/network
  notify: restart network

- name: Add new network
  template:
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - { src: 'network', dest: '/etc/sysconfig/network' }
  notify: restart network
