---
- name: Disable services
  shell: chkconfig {{ item }}
  with_items:
    - auditd off
    - postfix off
    - udev-post off
    - netfs off
    - nfslock off
    - rpcgssd off
    - rpcidmapd off
    - ip6tables off
