---
- name: WGET RPM
  command: wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm

- name: Rename download
  command: mv wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm ./wkhtmltopdf.rpm

- name: YUM local install whktmltopd
  command: yum localinstall -y wkhtmltopdf.rpm

- name: Remove wkhtmltopdf
  command: rm wkhtmltopdf.rpm

