---
- name: Add RPMs
  command: rpm -Uvh {{ item }}
  with_items:
    - http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

- name: Install Apache
  yum:
    name={{ item }}
    state=present
    enablerepo=remi
  with_items:
    - nfs-utils
    - nfs-utils-lib
    - httpd
  notify: restart apache

- name: Ensure httpd is running
  service:
    name=httpd
    state=started

- name: When booting start apache
  command: chkconfig {{ item }} on
  with_items:
    - httpd
