# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific aliases and functions

alias la="ll -A"
alias pac="php app/console"
alias getcomposer="curl -sS https://getcomposer.org/installer | php"