

- name: Install PHP5.4
  yum:
    name={{ item }}
    state=present
    enablerepo=remi
  with_items:
    - php
    - php-intl
    - php-apc
    - php-pdo
    - php-mysql
    - php-soap
    - php-imagick

- name: PHP Date Config
  shell: echo "date.timezone='UTC'" >> /etc/php.ini

- name: PHP APC Config
  shell: echo "apc.shm_size = 256M" >> /etc/php.ini

- name: Increase phpmyadmin upload size
  shell: echo "{{ item }}" >> /etc/php.ini
  with_items:
    - upload_max_filesize = 512M
    - post_max_size = 512M