---
- name: Blackfire Install pygpgme
  yum:
    name={{ item }}
    state=present
    enablerepo=remi
  with_items:
    - pygpgme

- name: Blackfire repo
  shell: curl "http://packages.blackfire.io/fedora/blackfire.repo" | sudo tee /etc/yum.repos.d/blackfire.repo

- name: Install Blackfire agent
  yum:
    name={{ item }}
    state=present
    enablerepo=remi
  with_items:
    - blackfire-agent

# TODO this needs to be interactive
- name: Blackfire agent register
  shell: blackfire-agent -register

- name: Blackfire agent restart
  shell: /etc/init.d/blackfire-agent restart

# TODO this needs to be interactive
- name: Blackfire config
  shell: blackfire config

- name: Install Blackfire php
  yum:
    name={{ item }}
    state=present
    enablerepo=remi
  with_items:
    - blackfire-php

#TODO check if possible via handler
- name: Restart apache
  shell: service httpd restart
