---
- name: Create cache and log dirs
  shell: mkdir {{ item }}
  with_items:
    - /srv/cache
    - /srv/logs

- name: Changing owner for srv
  shell: chown -R vagrant:vagrant /srv

- name: Preserve owner and group
  shell: chmod -R g+s /srv
