---
- name: Elasticsearch rpm
  command: rpm -Uvh {{ item }}
  with_items:
    - https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.0.noarch.rpm

- name: Start elasticsearch
  command: chkconfig {{ item }} on
  with_items:
    - elasticsearch
