---
- name: Install PHPMyAdmin
  yum:
    name=phpmyadmin
    state=present
    enablerepo=remi

- name: PHPMyAdmin timeout fix
  shell: echo "$cfg['ExecTimeLimit'] = 0;" >> /etc/phpMyAdmin/config.inc.php

- name: Remove old phpymadmin.conf & config.inc.php
  file:
    path={{ item }}
    state=absent
  with_items:
    - /etc/httpd/conf.d/phpMyAdmin.conf
    - /etc/phpMyAdmin/config.inc.php
  notify: restart apache

- name: Add new config.inc.php
  template:
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - { src: 'config.inc.php', dest: '/etc/phpMyAdmin/config.inc.php' }
  notify: restart apache
