---
- hosts: all
  remote_user: vagrant
  sudo: yes
  gather_facts: yes
  vars_files:
    - vars/settings.yml

  roles:
    - apache
    - mysql
    - php
    - misc
    - symfony
    - centos
    - redis
